<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/default.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['viewGallery'] = "Visa galleriet.";
$GLOBALS['TL_LANG']['MSC']['byGallery'] = "%s";
$GLOBALS['TL_LANG']['MSC']['artsize'] = "%s x %s %s";
$GLOBALS['TL_LANG']['MSC']['filterAll'] = "Alla";
$GLOBALS['TL_LANG']['MSC']['imageQty'] = "%s bilder";
$GLOBALS['TL_LANG']['ERR']['noDfGallery'] = "Vänligen installera dfGallery-modulen först.";
 
?>
