<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/modules.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Gallerier";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "Den här modulen hanterar bilder i gallerier.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Gallerier";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Gallerilista";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "Skapar en lista över galleriföremål från en samling.";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['0'] = "Gallerilista för sida";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['1'] = "Skapar en lista över galleriföremål från en samling som är kopplad till en sida.";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Gallerivisare";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['1'] = "Visar detaljer och ingående bilder för ett galleriföremål.";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Galleri enstaka";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['1'] = "Visar detaljer och bilder för ett enstaka galleriföremål.";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "Galleri dfGallery";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['1'] = "Visar bilderna från ett galleriföremål med hjälp av den Flash-baserade dfGallery.";
 
?>
