<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/tl_gallery_archive.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "Ange titel på gallerisamlingen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Beskrivning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "Ange en kort beskrivning av gallerisamlingen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Hoppa till sida";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['1'] = "Ange vilken sida som besökare ska förflyttas till när de klickar på en gallerilänk.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['0'] = "Sorteringsordning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['1'] = "Ange sorteringsordning för gallerisamlingen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['0'] = "Sidfilter";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['1'] = "Associerar denna gallerisamling med en sida sedan som används som filter i gallerilistor.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['0'] = "Artistgrupper";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['1'] = "Här du välja att filtrera gallerisamlingen på artistgrupper.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Aktivera kommentarer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['1'] = "Tillåt dina besökare att kommentera galleriföremål.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['0'] = "Meddela";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['1'] = "Ange vem som ska meddelas när någon skrivit en ny kommentar.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Layout för kommentarer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['1'] = "Välj en layout för dina kommentarer. Du kan lägga till egna mallar i mappen <em>templates</em>. Mallar för kommentarer börjar med <em>com_</em> och slutar med filändelsen <em>.tpl</em>.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Sorteringsordning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['1'] = "Ange sorteringsordning. Som standard är kommentarerna sorterade i stigande ordning och börjar med den äldsta.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Kommentarer per sida";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['1'] = "Ange antal kommentarer per sida (0=avaktivera paginering).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Granska kommentarer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['1'] = "Godkänn kommentarer innan dom publiceras på hemsidan.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "Tillåt BBCode";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['1'] = "Tillåt besökare att formatera sina kommentarer med BBCode.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Kräv inloggning för att kommentera";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['1'] = "Tillåt att endast inloggade medlemmar kan skapa kommentarer.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Avaktivera säkerhetsfrågan";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['1'] = "Använd detta alternativ endast om du har begränsat kommentarer till godkända användare.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['0'] = "Skydda galleriarkivet";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['1'] = "Visa bara galleriföremålen för vissa medlemsgrupper.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['0'] = "Tillåtna medlemsgrupper";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['1'] = "Här kan du välja vilka grupper som ska ha rätt att se galleriföremålen i denna samling.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['0'] = "Generera flöde";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['1'] = "Generera en RSS/Atom-flöde från gallerisamlingen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['0'] = "Flödesformat";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['1'] = "Välj flödesformat.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['0'] = "Språk";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['1'] = "Fyll i flödesspråk enligt ISO-639-standarden (t.ex. <em>sv</em> eller <em>sv-se</em>).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['0'] = "Exportinställningar";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['1'] = "Här han du välja vad som ska exporteras.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['0'] = "Maximalt antal poster";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['1'] = "Begränsa antalet exporterade poster. Lämna tomt eller ange 0 för att inkludera alla.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['0'] = "Bas-URL";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['1'] = "Ange Base URL med protokoll (dvs <em>http://</em>).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['0'] = "Flödesalias";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['1'] = "Här kan du ange ett unikt flödesnamn. En XML-fil kommer att genereras automatiskt i rootmappen på din Contao-installation (<em>namn.xml</em>).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['0'] = "Beskrivning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['1'] = "Ange en kort beskrivning av nyhetsflödet.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['0'] = "Versionsdatum";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['1'] = "Datum och tid för senaste version";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_asc'] = "Filnamn (stigande)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_desc'] = "Filnamn (fallande)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_asc'] = "Datum (stigande)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_desc'] = "Datum (fallande)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['meta'] = "Metafil (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['random'] = "Slumpmässig ordning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_admin'] = "Systemadministratör";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_author'] = "Galleriföremålets författare";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_both'] = "Författare och systemadministratör";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sorting'] = "Manuell sortering";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_asc'] = "Titel (alfabetisk)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Titel, beskrivning och hoppa till-sida";
$GLOBALS['TL_LANG']['tl_gallery_archive']['filter_legend'] = "Filterinställningar";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups_legend'] = "Artistgrupper";
$GLOBALS['TL_LANG']['tl_gallery_archive']['image_legend'] = "Standard bildinställning";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Kommentarer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected_legend'] = "Åtkomstskydd";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feed_legend'] = "RSS/Atom-flöde";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Ny gallerisamling";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Skapa en ny gallerisamling";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Redigera gallerisamling";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Redigera gallerisamling med ID %S";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Kopiera gallerisamling";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Kopera gallerisamling med ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Ta bort gallerisamling";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Ta bort gallerisamling med ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Gallerisamlingsdetaljer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Visa detaljer för gallerisamling med ID %s";
 
?>
