<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/tl_gallery.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "Ange en titel för galleriet.";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Gallerialias";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['1'] = "Gallerialias är ett unik referensnamn som kan användas istället för galleriets numeriska ID-nummer.";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "Ange ett datum för galleriet.";
$GLOBALS['TL_LANG']['tl_gallery']['author']['0'] = "Författare";
$GLOBALS['TL_LANG']['tl_gallery']['author']['1'] = "Ange galleriföremålets författare.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Plats";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "Ange platsens namn.";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['0'] = "Artist- eller fotograf-medlem";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['1'] = "Välj artist eller fotograf bland medlemmarna.";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['0'] = "Fysisk storlek";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['1'] = "Ange fysisk storlek som bredd, höjd och enhet.";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['0'] = "Media";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['1'] = "Ange mediatyp.";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['0'] = "Substrat";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['1'] = "Välj vilken typ av substrat som verket har skapats/tryckts på.";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Beskrivning";
$GLOBALS['TL_LANG']['tl_gallery']['description']['1'] = "Ange en kort beskrivning för galleriet.";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['0'] = "Affischbild";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['1'] = "Välj bild som ska användas som affischbild i galleriets listvyer.";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Galleribilder";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['1'] = "Välj en eller flera filer och/eller hela mappar från filarkivet.";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['0'] = "Åsidosätt standardinställningar för bilder";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['1'] = "Låter dig åsidosätta standardinställningar för bilder i samlingen.";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['0'] = "Bildbredd och höjd för affischbild";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['1'] = "Ange storlek och omformateringsmetod för bilden.";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['0'] = "Visa affischbild i fullstorlek";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['1'] = "Öppna affischbilden i fullstorlek i en lightbox.";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Bildbredd och höjd för galleribild";
$GLOBALS['TL_LANG']['tl_gallery']['size']['1'] = "Ange storlek och omformateringsmetod för bilden.";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Bildmarginal för galleribild";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['1'] = "Ange topp, höger, botten och vänster-marginal samt en enhet. <br />Bildmarginalen är avståndet mellan bilden och dess omgivning.";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Minibilder per rad";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['1'] = "Ange antalet minibilder per rad.";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Poster per sida";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['1'] = "Ange antalet poster per sida (0=stäng av pagineringsfunktionen).";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Sortera på";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "Ange en sorteringsordning.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Visa i fullstorlek";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['1'] = "Öppna bilden i fullstorlek i en lightbox genom att klicka på den.";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['0'] = "Stilmallsklass";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['1'] = "Här kan du ange en eller flera stilmallsklasser (CSS klasser).";
$GLOBALS['TL_LANG']['tl_gallery']['status']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_gallery']['status']['1'] = "Välj status för galleriföremålet.";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Avaktivera kommentarer";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['1'] = "Tillåt inte kommentarer från besökare för detta galleriföremål.";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['0'] = "Utvalt föremål";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['1'] = "Visar galleriföremålet i gallerilista över utvalda föremål.";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Publicerad";
$GLOBALS['TL_LANG']['tl_gallery']['published']['1'] = "Markera detta alternativ för att publicera galleriföremålet så att den visas för hemsidans besökare.";
$GLOBALS['TL_LANG']['tl_gallery']['start']['0'] = "Börja visa fr.o.m.";
$GLOBALS['TL_LANG']['tl_gallery']['start']['1'] = "Om du anger ett datum så börjar galleriföremålet visas på hemsidan från och med den valda dagen.";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['0'] = "Sluta visa fr.o.m.";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['1'] = "Om du anger ett datum så slutar galleriföremålet visas på hemsidan från och med den valda dagen.";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Filnamn (stigande)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Filnamn (fallande)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Datum (stigande)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Datum (fallande)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Metafil (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['random'] = "Slumpmässig ordning";
$GLOBALS['TL_LANG']['tl_gallery']['oil'] = "Olja";
$GLOBALS['TL_LANG']['tl_gallery']['acr'] = "Akryl";
$GLOBALS['TL_LANG']['tl_gallery']['ola'] = "Olja och akryl";
$GLOBALS['TL_LANG']['tl_gallery']['mpt'] = "Monoprint";
$GLOBALS['TL_LANG']['tl_gallery']['cpt'] = "Färgtryck";
$GLOBALS['TL_LANG']['tl_gallery']['cvs'] = "Duk";
$GLOBALS['TL_LANG']['tl_gallery']['ppr'] = "Papper";
$GLOBALS['TL_LANG']['tl_gallery']['pho'] = "Fotografi";
$GLOBALS['TL_LANG']['tl_gallery']['vnl'] = "Vinyl";
$GLOBALS['TL_LANG']['tl_gallery']['brd'] = "Spånskiva";
$GLOBALS['TL_LANG']['tl_gallery']['fab'] = "Fabriano";
$GLOBALS['TL_LANG']['tl_gallery']['avail'] = "Tillgänglig";
$GLOBALS['TL_LANG']['tl_gallery']['sold'] = "Såld";
$GLOBALS['TL_LANG']['tl_gallery']['resv'] = "Reserverad";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Titel och beskrivning";
$GLOBALS['TL_LANG']['tl_gallery']['poster_legend'] = "Affischbild";
$GLOBALS['TL_LANG']['tl_gallery']['gallery_legend'] = "Galleribilder";
$GLOBALS['TL_LANG']['tl_gallery']['groups_legend'] = "Artistgrupper";
$GLOBALS['TL_LANG']['tl_gallery']['expert_legend'] = "Expertinställningar";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Publiceringsinställningar";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Nytt galleri";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Skapa ett nytt galleri";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Redigera galleri";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Redigera galleri med ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Kopiera galleri";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Kopiera galleri med ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Ta bort galleri";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Ta bort galleri med ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Galleridetaljer";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Visa detaljer för galleri med ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['0'] = "Publicera / avpublicera galleri";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['1'] = "Publicera / avpublicera galleri med ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['0'] = "Redigera samlingens inställninar";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['1'] = "Redigera gallerisamlingens inställningar";
 
?>
