<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/tl_module.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Galleri";
$GLOBALS['TL_LANG']['tl_module']['gallery']['1'] = "Välj galleri som ska visas.";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Galleriarkiv";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['1'] = "Välj ett eller flera galleriarkiv";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "Metadata-fält";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['1'] = "Välj vilka metadata-fält som ska visas.";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Datumformat";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['1'] = "Ange ett datumformat så som det används av PHP-funktionen <em>date()</em>.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "Sorteringsordning";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['1'] = "Välj vilket fält som ska användas för att sortera gallerilistan.";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['0'] = "Aktivera filter";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['1'] = "Genom att aktivera filter kommer gallerilistor att svara på URL-filterparametrar.";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['0'] = "Lägg till filter-fält";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['1'] = "Välj vilka fält som ska kunna användas för filtrering av gallerilistan.";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['0'] = "Filtrering på villkor";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['1'] = "Välj vilka villkor som ska kunna användas för filtrering av gallerilistan.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "Totalt antal galleriföremål";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['1'] = "Här kan det totala antalet visade galleriföremål begränsas. Sätt till 0 för att visa alla.";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['0'] = "Enbart utvalda föremål";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['1'] = "Visa enbart föremål som markerats som utvalda i listan.";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['0'] = "Bildbredd och höjd för affischbild";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['1'] = "Ange storlek och omformateringsmetod för bilden.";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['0'] = "Visa affischbild i fullstorlek";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['1'] = "Öppna affischbilden i fullstorlek i en lightbox.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "Visa galleribilder";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['1'] = "Visa galleribilder.";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "Bildbredd och höjd för galleribild";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['1'] = "Ange storlek och omformateringsmetod för bilden.";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "Bildmarginal för galleribild";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['1'] = "Ange topp, höger, botten och vänster-marginal samt en enhet. <br />Bildmarginalen är avståndet mellan bilden och dess omgivning.";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['0'] = "Minibilder per rad";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['1'] = "Ange antal minibilder per rad.";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['0'] = "Poster per sida";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['1'] = "Ange antal poster per sida (0=stäng av pagineringsfunktionen).";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['0'] = "Sortera på";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['1'] = "Ange en sorteringsordning.";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['0'] = "Visa i fullstorlek";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['1'] = "Öppna bilden i fullstorlek i en lightbox genom att klicka på den.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['0'] = "Totalt antal galleriföremål";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['1'] = "Här kan det totala antalet visade galleriföremål begränsas. Sätt till 0 för att visa alla.";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "Gallerimall";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['1'] = "Här kan du välja gallerimall.";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Gallerititel";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['1'] = "Ange en titel för galleriet";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Bredd och höjd";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['1'] = "Ange bredden och höjden i pixlar för galleriet.";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['0'] = "Visningsintervall";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['1'] = "Ange visningsintervall i sekunder.";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "XML-mall";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['1'] = "Här kan du välja en XML-mall för initiering av galleriet.";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Paus vid start";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['1'] = "Starta inte bildspelet automatiskt.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['default'] = "Standard (gallerisamlingens inställning)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_desc'] = "Datum (senaste först)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_asc'] = "Datum (äldsta först)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Titel (alfabetiskt)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['sorting'] = "Manuell sortering";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Slumpmässig ordning";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_asc'] = "Filnamn (stigande)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_desc'] = "Filnamn (fallande)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['meta'] = "Metafil (meta.txt)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['author'] = "Författare";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Plats";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artist'] = "Artist eller fotograf";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artsize'] = "Föremålets storlek";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['medium'] = "Medium";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['substrate'] = "Substrat";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['comments'] = "Kommentarer";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['qty'] = "Bildkvalitet";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "dfGallery-inställningar";
$GLOBALS['TL_LANG']['tl_module']['filter_legend'] = "Filterinställningar";
 
?>
