<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/tl_member.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['description']['0'] = "Beskrivning";
$GLOBALS['TL_LANG']['tl_member']['description']['1'] = "Ange en beskrivning.";
$GLOBALS['TL_LANG']['tl_member']['detail_legend'] = "Övriga detaljer (Galleri-artist)";
 
?>
