<?php
/**
 * TL_ROOT/system/modules/gallery/languages/sv/tl_user.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Swedish translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Matz Särås (SuperMatz), http://www.xprofil.se 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['galleries']['0'] = "Gallerisamlingar";
$GLOBALS['TL_LANG']['tl_user']['galleries']['1'] = "Här kan du tilldela behörighet för en eller flera gallerisamlingar.";
$GLOBALS['TL_LANG']['tl_user']['galleryp']['0'] = "Galleribehörigheter";
$GLOBALS['TL_LANG']['tl_user']['galleryp']['1'] = "Här kan du definiera användarens behörigheter vid hantering av gallerier.";
$GLOBALS['TL_LANG']['tl_user']['gallery_legend'] = "Galleribehörigheter";
 
?>
