<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/default.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['viewGallery'] = "Visualizza la galleria";
$GLOBALS['TL_LANG']['MSC']['byGallery'] = "Foto scattate da %s";
$GLOBALS['TL_LANG']['MSC']['artsize'] = "%s x %s %s";
$GLOBALS['TL_LANG']['MSC']['filterAll'] = "Tutti";
$GLOBALS['TL_LANG']['MSC']['imageQty'] = "%s immagini";
$GLOBALS['TL_LANG']['ERR']['noDfGallery'] = "Occorre installare l'estensione dfGallery prima.";
 
?>
