<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/modules.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Gallerie immagini";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "Questo modulo gestisce le galerie di immagini.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Gallerie immagini";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Elenco gallerie immagini";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "Questo modulo elenca gli elementi galleria";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['0'] = "Elenco galleria per pagina";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['1'] = "adds a list of gallery items from a collection linked to a page.";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Visualizzatore galleria";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['1'] = "Questo modulo mostra tutte le immagini della galleria";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Singola galleria";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['1'] = "Questo modulo consente di creare un modulo per una galleria specifica.";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "Galleria dfGallery";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['1'] = "Questo modulo mostra tutte le immagini della galleria utilizzando il componente dfGallery";
 
?>
