<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/tl_gallery_archive.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "Inserire il titolo della galleria";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "Inserire una breve descrizione dell'archivio";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Salta alla pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['1'] = "Seleziona la pagina alla quale i visitatori saranno reindirizzati cliccando su una galleria immagini.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['0'] = "Ordinamento";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['1'] = "Imposta l'ordinamento di default della collezione di gallerie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['0'] = "Pagina filtro";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['1'] = "Associa questa galleria ad una pagina da utilizzare come filtro.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['0'] = "Gruppo artisti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['1'] = "Qui è possibile filtrare gli artisti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Abilita commenti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['1'] = "Abilita i visitatori a commentare le galleria immagini.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['0'] = "Notifica";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['1'] = "Selezionare a chi inviare il commento quando questo viene aggiunto.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Layout dei commenti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['1'] = "Seleziona un layout per i commenti. I file template dei commenti iniziano per <em>com_</em>";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Ordina per";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['1'] = "Seleziona l'ordine di visualizzazione";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Elementi per pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['1'] = "Indicare il numero di elementi per pagina (0 = disabilita l'impaginazione)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Modera";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['1'] = "Approva i commenti prima che vengano visualizzati sul sito web.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "Abilita BBCode";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['1'] = "Abilita i BBCode nei commenti per i visitatori.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Richiedi login";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['1'] = "Non abilitare gli utenti anonimi a creare commenti.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Disabilita domanda di sicurezza";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['1'] = "Seleziona questa opzione se desideri disabilitare la domanda di sicurezza (non raccomandato).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['0'] = "Protezione archivio";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['1'] = "Mostra gli elementi della galleria solo a certi gruppi.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['0'] = "Abilita solo gruppi";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['1'] = "Solo i gruppi selezionati potranno accedere agli elementi della galleria.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['0'] = "Genera un feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['1'] = "Genera un feed RSS/Atom per l'archivio delle gallerie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['0'] = "Formato feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['1'] = "Seleziona un formato per il feed.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['0'] = "Lingua";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['1'] = "Inserisci la lingua secondo il formato RFC1766 (es: <em>it</em>, <em>en</em>, <em>en-us</em>).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['0'] = "Impostazioni export";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['1'] = "Qui si può selezionare cosa che sarà esportato.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['0'] = "Massimo numero di elementi";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['1'] = "Limita il numero di elementi esportati. Lasciare vuoto o inserire 0 per includere tutti gli elementi.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['0'] = "URL di base";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['1'] = "Inserisci un URL di base con protocollo incluso. (<em>http://</em>)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['0'] = "Alias feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['1'] = "È possibile inserire un nome univoco per il feed. Verrà generato automaticamente un file XML nella cartella principale di Contao (<em>name.xml</em>)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['1'] = "Inserisci una breve descrizione del feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['0'] = "Data aggiornamento";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['1'] = "Data e ora dell'ultimo aggiornamento";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_asc'] = "Nome file (ascendente)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_desc'] = "Nome file (discendente)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_asc'] = "Data (ascendente)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_desc'] = "Data (discendente)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['meta'] = "Meta file (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['random'] = "Ordine casuale";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_admin'] = "Amministratore di sistema";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_author'] = "Autore della galleria";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_both'] = "Autore e amministratore di sistema";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sorting'] = "Ordine manuale";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_asc'] = "Titolo (alfabetico)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Titolo, descrizione e ridirezione pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['filter_legend'] = "Impostazioni filtro";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups_legend'] = "Gruppi artisti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['image_legend'] = "Configurazione immagine di default";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Commenti";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected_legend'] = "Protezione accesso";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feed_legend'] = "RSS/Atom feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Nuovo archivio gallerie immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Crea un nuovo archivio galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Modifica l'archivio galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Modifica l'archivio galleria immagini ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Copia l'archivio galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Copia l'archivio galleria immagini ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Elimina l'archivio galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Elimina l'archivio galleria immagini ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Dettagli archivio galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Mostra i dettagli archivio galleria immagini ID %s";
 
?>
