<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/tl_gallery.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "Indicare il titolo della galleria";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Alias galleria";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['1'] = "Un alias è un riferimento univoco alla galleria immagini che può essere richiamato al posto del ID.";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Data";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "Inserire la data della galleria.";
$GLOBALS['TL_LANG']['tl_gallery']['author']['0'] = "Autore";
$GLOBALS['TL_LANG']['tl_gallery']['author']['1'] = "Qui è possibile cambiare l'autore degli elementi della galleria.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Luogo";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "Luogo in cui sono state scattate le foto.";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['0'] = "Artista o fotografo";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['1'] = "Selezionare l'artista o il fotografo";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['0'] = "Dimensioni opera";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['1'] = "Indicare le dimensioni dell'opera";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['0'] = "Materiale";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['1'] = "Indiacre il materiale di cui è composto il dipinto o la stampa";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['0'] = "Substrato";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['1'] = "Indicare il substrato con cui è dipinta l'opera o è stampata la foto.";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_gallery']['description']['1'] = "Indicare una breve descrizione della galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['0'] = "Immagine poster";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['1'] = "Selezionare l'immagine di anteprima usata dalla lista della galleria.";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Origine file";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['1'] = "Selezionare uno o più file o cartelle (i file nelle sottocartelle varranno selezionati in automatico).";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['0'] = "Sovrascrivi le impostazioni di default delle immagini";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['1'] = "Sovrascrive le impostazioni delle immagini della collezione della galleria.";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['0'] = "Largezza ed altezza immagine poster";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['1'] = "Indicare larghezza e altezza immagine oppure entrambe, per ridimensionare l'immagine.";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['0'] = "Visione intera immagine poster";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['1'] = "Selezionando questa opzione, cliccando sull'immagine, questa potrà essere vista a dimensioni intere.";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Larghezza e altezza immagine";
$GLOBALS['TL_LANG']['tl_gallery']['size']['1'] = "Inserire la larghezza immagine o l'altezza, oppure entrambe le misure, per ridimensionare l'immagine. Se si lasciano questi campi vuoti verrà utilizzata la dimensione originale.";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Margine immagine";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['1'] = "Inserisci i margini top, right, bottom e left con le rispettive unità. Il margine è lo spazio tra l'immagine e gli elementi vicini.";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Miniature per riga";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['1'] = "Indicare il numero di miniature per riga.";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Elementi per pagina";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['1'] = "Indicare il numero di elementi per pagina (0 = disabilita l'impaginazione)";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Ordinamento";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "Indicare l'ordinamento da utilizzare.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Visione dimensione intera";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['1'] = "Cliccando sull'immagine verrà visualizzata a dimensione intera.";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['0'] = "Classe CSS";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['1'] = "Indicare la classe CSS";
$GLOBALS['TL_LANG']['tl_gallery']['status']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_gallery']['status']['1'] = "Indicare lo status dell'elemento della galleria";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Disabilita commenti";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['1'] = "Disabilita i commenti per una particolare galleria immagine.";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['0'] = "Elemento in evidenza";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['1'] = "Mostra la galleria tra quelle in evidenza.";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_gallery']['published']['1'] = "Finché questa opzione non è selezionata la galleria immagini non sarà visibile suo sito.";
$GLOBALS['TL_LANG']['tl_gallery']['start']['0'] = "Mostra dal giorno";
$GLOBALS['TL_LANG']['tl_gallery']['start']['1'] = "Se inserisci una data qui, la galleria sarà visibile da quella data in poi. Prima di quella data, non sarà pubblicata.";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['0'] = "Fino al giorno";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['1'] = "Se inserisci una data qui, la galleria non sarà più visibile a partire da quella data.";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Nome file (ascendente)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Nome file (discendente)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Data (ascendente)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Data (discendente)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Meta file (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['random'] = "Ordine casuale";
$GLOBALS['TL_LANG']['tl_gallery']['oil'] = "Olio";
$GLOBALS['TL_LANG']['tl_gallery']['acr'] = "Acrilico";
$GLOBALS['TL_LANG']['tl_gallery']['ola'] = "Olio ed aclilico";
$GLOBALS['TL_LANG']['tl_gallery']['mpt'] = "Monocromata";
$GLOBALS['TL_LANG']['tl_gallery']['cpt'] = "Stampa a colori";
$GLOBALS['TL_LANG']['tl_gallery']['cvs'] = "Tela";
$GLOBALS['TL_LANG']['tl_gallery']['ppr'] = "Carta";
$GLOBALS['TL_LANG']['tl_gallery']['pho'] = "Foto";
$GLOBALS['TL_LANG']['tl_gallery']['vnl'] = "Vinile";
$GLOBALS['TL_LANG']['tl_gallery']['brd'] = "Cornice";
$GLOBALS['TL_LANG']['tl_gallery']['fab'] = "Fabriano";
$GLOBALS['TL_LANG']['tl_gallery']['avail'] = "Disponibile";
$GLOBALS['TL_LANG']['tl_gallery']['sold'] = "Venduto";
$GLOBALS['TL_LANG']['tl_gallery']['resv'] = "Prenotato";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Titolo, fotografo, data luogo e descrizione";
$GLOBALS['TL_LANG']['tl_gallery']['poster_legend'] = "Immagine poster";
$GLOBALS['TL_LANG']['tl_gallery']['gallery_legend'] = "Immagini galleria";
$GLOBALS['TL_LANG']['tl_gallery']['groups_legend'] = "Gruppo artisti";
$GLOBALS['TL_LANG']['tl_gallery']['expert_legend'] = "Configurazione avanzata";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Impostazione pubblicazione";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Nuova galleria immagini";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Crea una nuova galleria";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Modifica la galleria";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Modifica la galleria ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Copia la galleria";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Copia la galleria ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Elimina galleria";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Elimina galleria ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Dettagli galleria";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Mostra i dettagli della galleria ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['0'] = "Pubblica/disabilita galleria";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['1'] = "Pubblica/disabilita galleria ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['0'] = "Modifica impostazioni collezione";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['1'] = "Modifica le impostazioni della collezione";
 
?>
