<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/tl_member.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_member']['description']['1'] = "Indicare una descrizione";
$GLOBALS['TL_LANG']['tl_member']['detail_legend'] = "Dettagli aggiuntivi";
 
?>
