<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/tl_module.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Galleria immagini";
$GLOBALS['TL_LANG']['tl_module']['gallery']['1'] = "Selezionare la galleria da mostrare";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Archio gallerie immagini";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['1'] = "Seleziona una o più archivi";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "Campi disponibili";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['1'] = "Si prega di selezionare quale campo sarà visualizzato";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Formato data";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['1'] = "Inserire il formato data utilizzando le opzioni della funzione PHP <em>date()</em>";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "Ordina per";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['1'] = "Seleziona il campo che sarà usato per ordinare la galleria immagini";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['0'] = "Abilita il supporto filtro";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['1'] = "Abilita la lista delle gallerie a rispondere i parametri del filtro.";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['0'] = "Aggiungi campo filtro";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['1'] = "Aggiungi i seguenti campi filtro alla galleria immagini.";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['0'] = "Filtra in base alle condizioni";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['1'] = "Seleziona i campi che definiscono il filtro";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "Numero di gallerie da visualizzare";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['1'] = "Seleziona il numero di gallerie da visualizzare (0 = per visualizzare tutte le gallerie).";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['0'] = "Elementi in evidenza solo";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['1'] = "Mostra solo le gallerie in evidenza";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['0'] = "Larghezza ed altezza dell'immagine poster";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['1'] = "E' possibile indicare le dimensioni dell'immagine poster per poterla ridimensionare (opzionale)";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['0'] = "Visualizza a dimensioni reali";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['1'] = "Visualizza l'immagine a dimensioni reali";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "Mostra miniatura di anteprima";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['1'] = "Selezionare questa opzione per aggiungere l'anteprima (di default solo la prima riga) a ciascun elemento galleria. È possibile impostare le dimensioni delle miniature di seguito.";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "Larghezza e altezza immagine";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['1'] = "Se si inserisce solo la larghezza o l'altezza dell'immagine, essa verrà ridimensionata proporzionalmente. Se si immettono entrambe le misure e l'immagine supera i limiti, quest'ultima verrà tagliata. Se si lasciano vuoti i campi verrà visualizzata con la dimensione originale.";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "Margine immagine";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['1'] = "Inserisci i margini top, right, bottom e left con le rispettive unità. Il margine è lo spazio tra l'immagine e gli elementi vicini.";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['0'] = "Miniature per riga";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['1'] = "Indicare il numero delle miniature per riga";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['0'] = "Elementi per pagina";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['1'] = "Indicare il numero di elementi per pagina";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['0'] = "Ordinamento";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['1'] = "Selezionare il tipo di ordinamento";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['0'] = "Visione dimensione intera";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['1'] = "Cliccando sull'immagine verrà visualizzata a dimensione intera.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['0'] = "Mostra numero totale immagini";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['1'] = "Indicare il numero massimo di immagini. Indicare 0 per mostrarle tutte.";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "Layout galleria";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['1'] = "Selezionare un layout. Puoi aggiungere altri layouts personalizzati inserendoli nella cartella <em>templates</em>. I template delle gallerie immagini hanno il prefisso <em>gallery_</em> e richiedono come estensione <em>.tpl</em>";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Titolo galleria";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['1'] = "Inserire il titolo della galleria immagini";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Larghezza e altezza";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['1'] = "Inserire larghezza e altezza del filmato Flash";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['0'] = "Intervallo slide";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['1'] = "Inserire l'intervallo tra le immagini.";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "XML template";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['1'] = "Scegliere un template XML per configurare la galleria";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Non avviare automaticamente";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['1'] = "Non avviare automaticamente la galleria immagini al caricamento della pagina";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['default'] = "Default (Impostazioni collezione gallerie)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_desc'] = "Data (più recente prima)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_asc'] = "Data (meno recente prima)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Titolo (alfabetico)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['sorting'] = "Ordine manuale";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Casuale (non ordinato)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_asc'] = "Nome file (ascendente)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_desc'] = "Nome file (discendente)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['meta'] = "Meta file (meta.txt)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['author'] = "Autore";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Luogo";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Data";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artist'] = "Artista o fotografo";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artsize'] = "Dimensioni opera";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['medium'] = "Materiale";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['substrate'] = "Substrato";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['comments'] = "Commenti";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['qty'] = "Qualità immagine";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "Impostazione dfGallery";
$GLOBALS['TL_LANG']['tl_module']['filter_legend'] = "Impostazioni filtro";
 
?>
