<?php
/**
 * TL_ROOT/system/modules/gallery/languages/it/tl_user.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['galleries']['0'] = "Autorizzazioni archivi Galleria Immagini";
$GLOBALS['TL_LANG']['tl_user']['galleries']['1'] = "Autorizzazioni di accesso alle gallerie immagini";
$GLOBALS['TL_LANG']['tl_user']['galleryp']['0'] = "Autorizzazioni Galleria Immagini";
$GLOBALS['TL_LANG']['tl_user']['galleryp']['1'] = "Qui è possibile definire i permessi della galleria";
$GLOBALS['TL_LANG']['tl_user']['gallery_legend'] = "Autorizzazioni Galleria Immagini";
 
?>
