<?php
/**
 * TL_ROOT/system/modules/gallery/languages/de/modules.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Galerien";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "Dieses Modul verwaltet Bilder in Galerien.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Galerien";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Galerie-Liste";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "Dieses Modul listet Galerie-Einträge nach ihren Galerie-Archiven auf.";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Galerie-Ansicht";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['1'] = "Dieses Modul zeigt eine ausgewählte Galerie in einer Galerie-Liste.";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Einzel-Galerie";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['1'] = "Dieses Modul erlaubt es Ihnen, ein Modul für eine bestimmte Galerie zu erstellen, so dass Sie es in Nachrichten, Ereignisse oder Artikel als Insert-Tag <em>{‎{insert_module::ID}}</em> einbinden können.";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "Galerie dfGallery";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['1'] = "Dieses Modul zeigt alle Galerie-Bilder an (unter Verwendung der Flash-basierten dfGallery), wenn Sie auf eine Galerie-Liste klicken.";
 
?>
