<?php
/**
 * TL_ROOT/system/modules/gallery/languages/de/tl_gallery_archive.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "Bitte geben Sie den Titel des Galerie-Archives an.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "Bitte geben Sie eine kurze Beschreibung für das Galerie-Archiv ein.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Gehe zu Seite";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['1'] = "Bitte wählen Sie die Seite aus, zu der Besucher geleitet werden, wenn Sie auf einen Galerie-Link klicken.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Kommentare aktivieren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['1'] = "Erlauben Sie Ihren Gästen, neue Einträge zu kommentieren.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Aussehen der Kommentare";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['1'] = "Bitte wählen Sie ein Kommentar-Aussehen aus. Template-Dateien beginnen mit <em>com_</em>.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Sortier-Reihenfolge";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['1'] = "Bitte wählen Sie die Sortier-Reihenfolge aus.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Einträge pro Seite";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['1'] = "Bitte geben Sie die Anzahl der Kommentare pro Seite ein (0 = Paginierung ausschalten).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Moderieren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['1'] = "Überprüfen Sie Kommentare, bevor sie auf der Webseite angezeigt werden.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "BBCode erlauben";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['1'] = "Erlauben Sie Gästen, BBCode zum Formatieren ihrer Kommentare zu verwenden.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Login verlangen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['1'] = "Gästen verbieten, Kommentare zu erstellen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Sicherheitsabfrage deaktivieren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['1'] = "Wählen Sie diese Option aus, um die Sicherheitsabfrage auszuschalten (nicht empfohlen).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['ascending'] = "aufsteigend";
$GLOBALS['TL_LANG']['tl_gallery_archive']['descending'] = "absteigend";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Titel, Beschreibung und Weiterleitungsseite";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Kommentare";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Neues Galerie-Archiv";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Ein neues Galerie-Archiv erstellen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Galerie-Archiv bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Galerie-Archiv ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Galerie-Archiv kopieren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Galerie-Archiv ID %s kopieren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Galerie-Archiv löschen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Galerie-Archiv ID %s löschen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Eigenschaften des Galerie-Archives";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Eigenschaften des Galerie-Archives anzeigen";
 
?>
