<?php
/**
 * TL_ROOT/system/modules/gallery/languages/de/tl_gallery.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "Bitte geben Sie den Titel der Galerie ein.";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Galerie-Alias";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['1'] = "Der Galerie-Alias ist eine eindeutige Referenz auf die Galerie, der anstatt der Ereignis-ID aufgerufen werden kann.";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "Bitte geben Sie das Datum der Galerie ein.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Ort";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "Bitte geben Sie den Ortsnamen ein.";
$GLOBALS['TL_LANG']['tl_gallery']['photographer']['0'] = "Fotograf";
$GLOBALS['TL_LANG']['tl_gallery']['photographer']['1'] = "Bitte geben Sie den Namen des Fotografen ein.";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_gallery']['description']['1'] = "Bitte geben Sie eine kurze Beschreibung für die Galerie ein.";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Quelldateien";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['1'] = "Bitte wählen Sie eine oder mehrere Dateien oder Ordner aus (Dateien innerhalb eines Ordner werden automatisch eingebunden).";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Miniansichten pro Zeile";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['1'] = "Bitte geben Sie die Anzahl der Miniansichten pro Zeile ein.";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Sortierung nach";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "Bitte wählen Sie eine Sortier-Reihenfolge aus.";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Elemente pro Seite";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['1'] = "Bitte geben Sie die Anzahl der Elemente pro Seite ein (0 = Paginierung deaktivieren)";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Bildrand";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['1'] = "Bitte geben Sie den oberen, rechten, unteren und linken Rand und die Maßeinheit ein. Der Bildrand ist der Platz zwischen einem Bild und seinem Nachbarelement.";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Bildbreite und -höhe";
$GLOBALS['TL_LANG']['tl_gallery']['size']['1'] = "Bitte geben Sie entweder die Bildbreite, die Bildhöhe oder beide Maße ein, um das Bildgröße zu verändern. Wenn Sie beide Felder leer lassen, wird die Original-Bildgröße angezeigt.";
$GLOBALS['TL_LANG']['tl_gallery']['autorotate']['0'] = "Automatische Drehung der Thumbnails";
$GLOBALS['TL_LANG']['tl_gallery']['autorotate']['1'] = "Wählen Sie diese Option aus, wenn Sie sicher gehen möchten, dass gedrehte Fotografien mit Hilfe von gedrehten Größenabmessungen angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Vollansicht";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['1'] = "Wenn Sie diese Option auswählen, kann das Bild durch Anklicken in voller Größe angezeigt werden.";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Veröffentlicht";
$GLOBALS['TL_LANG']['tl_gallery']['published']['1'] = "Die Galerie wird solange nicht auf Ihrer Webseite angezeigt, bis sie veröffentlicht ist.";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Kommentare deaktivieren.";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['1'] = "Deaktivieren Sie Kommentare für diesen speziellen Galerieeintrag.";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Dateiname (aufsteigend)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Dateiname (absteigend)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Datum (aufsteigend)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Datum (absteigend)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Meta-Datei (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Titel, Fotograf, Datum, Ort und Beschreibung";
$GLOBALS['TL_LANG']['tl_gallery']['source_legend'] = "Dateien und Ordner";
$GLOBALS['TL_LANG']['tl_gallery']['image_legend'] = "Bildeinstellungen";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Veröffentlichungseinstellungen";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Neue Galerie";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Eine neue Galerie erstellen";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Galerie bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Galerie ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Galerie kopieren";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Galerie ID %s kopieren";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Galerie löschen";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Galerie ID %s löschen";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Galerie-Eigenschaften";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Eigenschaften der Galerie ID %s anzeigen";
 
?>
