<?php
/**
 * TL_ROOT/system/modules/gallery/languages/de/tl_module.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Galerie";
$GLOBALS['TL_LANG']['tl_module']['gallery']['1'] = "Bitte wählen Sie eine Galerie zur Ansicht aus.";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Galerie-Archive";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['1'] = "Bitte wählen Sie ein oder mehrere Galerie-Archiv(e) aus.";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "Galerie-Layout";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['1'] = "Bitte wählen Sie ein neues Layout aus. Sie können individuelle Galerie-Layouts zum Ordner <em>templates</em> hinzufügen. Galerie-Template-Dateien beginnen mit <em>gallery_</em> und benötigen die Dateierweiterung <em>.tpl</em>.";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "Meta-Datenfelder";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['1'] = "Bitte wählen Sie aus, welche Meta-Datenfelder der Galerie angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Format des Datums";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['1'] = "Bitte geben Sie ein Datumsformat laut der PHP <em>date()</em> Funktion ein.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "Sortierfeld";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['1'] = "Wählen Sie welches Feld verwendet wird, um die Galerie-Liste zu sortieren.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showQuantity']['0'] = "Gesamtanzahl der Bilder anzeigen";
$GLOBALS['TL_LANG']['tl_module']['gallery_showQuantity']['1'] = "Wenn Sie diese Option verwenden, wird die Anzahl der Bilder neben jedem Galerieeintrag angezeigt.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "Anzahl der Galerien anzeigen";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['1'] = "Bitte wählen Sie die Anzahl der Galerie-Einträge, die angezeigt werden sollen (0 = Anzeige aller Galerie-Einträge).";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "Miniansicht-Vorschau anzeigen";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['1'] = "Wählen Sie diese Option aus, um bei jedem Galerie-Eintrag eine Vorschau der Miniansicht anzuzeigen. Sie können die Größe der Miniansicht unten bestimmen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showRandom']['0'] = "Anzeige nur eines zufälligen Bildes";
$GLOBALS['TL_LANG']['tl_module']['gallery_showRandom']['1'] = "Wenn Sie diese Option wählen, wird für jeden Galerie-Eintrag ein einzelnes und zufällig ausgewähltes Bild die Miniansicht sein.";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "Bildrand";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['1'] = "Bitte geben Sie den oberen, rechten, unteren und linken Rand und die Maßeinheit ein. Der Bildrand ist der Platz zwischen einem Bild und seinem Nachbarelement.";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "Bildbreite und -höhe";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['1'] = "Bitte geben Sie entweder die Bildbreite, die Bildhöhe oder beide Maße ein, um das Bildgröße zu verändern. Wenn Sie beide Felder leer lassen, wird die Original-Bildgröße angezeigt.";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Titel der Galerie";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['1'] = "Bitte geben Sie einen Titel für die Galerie ein.";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Breite und Höhe";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['1'] = "Bitte geben Sie die Breite und Höhe des Flash-Films ein.";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['0'] = "Slide-Intervall";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['1'] = "Bitte geben Sie das Slide-Intervall in Sekunden ein.";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "XML-Template";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['1'] = "Bitte geben Sie ein XML-Template für die Initialisierung der Galerie ein.";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Pause beim Start";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['1'] = "Starten Sie die Slideshow nicht standardmäßig.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date'] = "Datum (zuletzt zuerst)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Titel (alphabetisch)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Zufällig (unsortiert)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Ort";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['photographer'] = "Fotograf";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['description'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "dfGallery Einstellungen";
 
?>
