<?php
/**
 * TL_ROOT/system/modules/gallery/languages/de/tl_user.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['galleries']['0'] = "Galerie-Archive";
$GLOBALS['TL_LANG']['tl_user']['galleries']['1'] = "Bitte wählen Sie die Galerie-Archive aus, die Sie für den Benutzer aktivieren möchten.";
$GLOBALS['TL_LANG']['tl_user']['gallery_legend'] = "Galerie-Berechtigungen";
 
?>
