<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/default.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['viewGallery'] = "Bekijk de galerij.";
$GLOBALS['TL_LANG']['MSC']['byGallery'] = "%s";
$GLOBALS['TL_LANG']['MSC']['artsize'] = "%s x %s %s";
$GLOBALS['TL_LANG']['MSC']['filterAll'] = "Allemaal";
$GLOBALS['TL_LANG']['MSC']['imageQty'] = "%s afbeeldingen";
$GLOBALS['TL_LANG']['ERR']['noDfGallery'] = "Installeer eerst de dfGallery extensie.";
 
?>
