<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/modules.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Galerijen";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "Met deze module beheert u afbeeldingen en galerijen.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Galerijen";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Galerij lijst";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "voeg een lijst met galerij items uit een collectie toe.";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['0'] = "Galerij lijst per pagina";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['1'] = "voeg een lijst met galerij items uit een collectie toe gekoppeld aan een pagina.";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Galerij lezer";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['1'] = "laat de details en afbeeldingen van alle galerij items zien.";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Enkele galerij";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['1'] = "laat de details en afbeeldingen van een enkel galerij item zien.";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "dfGallery galerij";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['1'] = "laat de afbeeldingen van een galerij item zien middels de op flash gebasseerde dfGallery.";
 
?>
