<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/tl_comments.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_comments']['tl_gallery'] = "Galerij";
 
?>
