<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/tl_gallery.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "Geef een titel op voor de galerij.";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Galerij alias";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['1'] = "De galerij alias is een unieke referentie naar de galerij die opgeroepen kan worden i.p.v. de galerij ID.";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Datum";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "Vul de datum van de galerij in.";
$GLOBALS['TL_LANG']['tl_gallery']['author']['0'] = "Auteur";
$GLOBALS['TL_LANG']['tl_gallery']['author']['1'] = "Wijzig de auteur van het galerij item.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Locatie";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "Geef de locatie op.";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['0'] = "Kunstenaar of fotograaf";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['1'] = "Selecteer de kunstenaar of fotograaf (leden).";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['0'] = "Afmetingen van het werk";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['1'] = "Vul de breedte, hoogte en eenheid in.";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['0'] = "Medium";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['1'] = "Vul het medium in zoals schilderij of print.";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['0'] = "Materiaal";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['1'] = "Vul het materiaal in waarop is geschilderd of waarop de afbeeldingen zijn geprint.";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_gallery']['description']['1'] = "Geef een korte omschrijving voor de galerij.";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['0'] = "Poster afbeelding";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['1'] = "Selecteer de poster afbeelding die voor deze galerij gebruikt wordt in de lijstweergave.";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Galerij afbeeldingen";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['1'] = "Selecteer de afbeeldingen en/of mappen (afbeeldingen in mappen worden automatisch inbegrepen).";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['0'] = "Overschrijf de standaard afbeeldingsinstellingen";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['1'] = "Mogelijkheid om de afbeeldingsinstellingen van de galerij collectie te overschrijven.";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['0'] = "Poster afbeeldingsbreedte- en hoogte";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['1'] = "Vul of de afbeeldingsbreedte, de afbeeldingshoogte of beide formaten in om het formaat aan te passen. Wanneer je beide velden leeg laat zal het originele formaat worden weergegeven.";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['0'] = "Poster ware grootte /nieuw venster";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['1'] = "Open de afbeelding op ware grootte door er op te klikken.";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Galerij afbeeldingsbreedte- en hoogte";
$GLOBALS['TL_LANG']['tl_gallery']['size']['1'] = "Vul of de afbeeldingsbreedte, de afbeeldingshoogte of beide formaten in om het formaat aan te passen. Wanneer je beide velden leeg laat zal het originele formaat worden weergegeven.";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Galerij afbeeldingsmarge";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['1'] = "Geef een marge op voor boven, rechts, onder, en links.";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Thumbnails per rij";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['1'] = "Geef het aantal thumbnails per rij op.";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Items per pagina";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['1'] = "Geef het aantal items per pagina op (0=uitzetten).";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Sorteer op";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "Selecteer de sorteervolgorde.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Ware grootte /nieuw venster";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['1'] = "Open de afbeelding op ware grootte door er op te klikken.";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['0'] = "CSS class";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['1'] = "Hier kunt u één of meerdere classes instellen.";
$GLOBALS['TL_LANG']['tl_gallery']['status']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_gallery']['status']['1'] = "Selecteer de status van het galerij item.";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Sta reacties niet toe";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['1'] = "Sta reacties voor dit galerij item niet toe.";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['0'] = "Item eigenschappen";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['1'] = "Geef dit galerij item in een galerij lijst met bepaalde eigenschappen weer.";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Publiceer item";
$GLOBALS['TL_LANG']['tl_gallery']['published']['1'] = "Het galerij item is slechts zichtbaar op uw website als u deze optie selecteert.";
$GLOBALS['TL_LANG']['tl_gallery']['start']['0'] = "Toon vanaf";
$GLOBALS['TL_LANG']['tl_gallery']['start']['1'] = "Als u hier een datum invoert wordt dit galerij item niet voor deze datum getoond op de website.";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['0'] = "Toon tot";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['1'] = "Galerij item niet tonen op de website op en na deze dag.";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Bestandsnaam (oplopend)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Bestandsnaam (aflopend)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Datum (oudste eerst)'";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Datum (laatste eerst)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Meta bestand (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['random'] = "Willekeurige volgorde";
$GLOBALS['TL_LANG']['tl_gallery']['oil'] = "Olie";
$GLOBALS['TL_LANG']['tl_gallery']['acr'] = "Acryl";
$GLOBALS['TL_LANG']['tl_gallery']['ola'] = "Olie en acryl";
$GLOBALS['TL_LANG']['tl_gallery']['mpt'] = "Zwart/wit print";
$GLOBALS['TL_LANG']['tl_gallery']['cpt'] = "Kleur print";
$GLOBALS['TL_LANG']['tl_gallery']['cvs'] = "Doek";
$GLOBALS['TL_LANG']['tl_gallery']['ppr'] = "Papier";
$GLOBALS['TL_LANG']['tl_gallery']['pho'] = "Foto";
$GLOBALS['TL_LANG']['tl_gallery']['vnl'] = "Linnen";
$GLOBALS['TL_LANG']['tl_gallery']['brd'] = "Karton";
$GLOBALS['TL_LANG']['tl_gallery']['fab'] = "Katoen";
$GLOBALS['TL_LANG']['tl_gallery']['avail'] = "Beschikbaar";
$GLOBALS['TL_LANG']['tl_gallery']['sold'] = "Verkocht";
$GLOBALS['TL_LANG']['tl_gallery']['resv'] = "Gereserveerd";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Titel en andere beschrijvende informatie";
$GLOBALS['TL_LANG']['tl_gallery']['poster_legend'] = "Poster afbeelding";
$GLOBALS['TL_LANG']['tl_gallery']['gallery_legend'] = "Galerij afbeeldingen";
$GLOBALS['TL_LANG']['tl_gallery']['groups_legend'] = "Kunstenaars groepen";
$GLOBALS['TL_LANG']['tl_gallery']['expert_legend'] = "Expert instellingen";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Publiceer instellingen";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Nieuwe galerij";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Maak een nieuwe galerij";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Bewerk galerij";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Bewerk galerij ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Dupliceer galerij";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Dupliceer galerij ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Verwijder galerij";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Verwijder galerij ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Galerij details";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Toon details van galerij ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['0'] = "Publiceer/depubliceer galerij";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['1'] = "Publiceer/depubliceer galerij ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['0'] = "Bewerk collectie instellingen";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['1'] = "Bewerk de collectie instellingen";
 
?>
