<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/tl_gallery_archive.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "Geef een titel op voor deze galerij collectie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "Geef een korte omschrijving op voor deze galerij collectie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Ga naar pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['1'] = "Selecteer de pagina waarnaar een gebruiker wordt verder geleid na het klikken op een galerij link.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['0'] = "Sorteermodus";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['1'] = "Hier kunt u de sorteermodus kiezen voor deze galerij collectie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['0'] = "Pagina filter";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['1'] = "Associeer deze galerij collectie met een pagina om te gebruiken als filter in de galerij lijst.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['0'] = "Kunstenaars groepen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['1'] = "Hier kunt u de selectie van kunstenaars groepen filteren.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Reacties toestaan";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['1'] = "Sta uw bezoekers toe reacties bij galerij items te plaatsen.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['0'] = "Kennisgeving";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['1'] = "Kies wie u op de hoogte wilt stellen wanneer er nieuwe reacties zijn toegevoegd.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Reacties layout";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['1'] = "Selecteer een reactie template. Reactie template bestanden beginnen met <em>com_</em>.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Sorteer volgorde";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['1'] = "Standaard worden reacties oplopend gesorteerd, beginnend met de oudste.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Reacties per pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['1'] = "Geef het aantal resultaten per pagina op.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Modereer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['1'] = "Reacties goedkeuren vooraleer ze op de website worden getoond.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "BBCode toestaan";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['1'] = "Laat bezoekers toe om BBCode te gebruiken om hun reacties op te maken.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Inloggen verplicht om te kunnen reageren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['1'] = "Toestaan om alleen geregistreerde gebruikers reacties te laten geven.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Veiligheidsvraag uitzetten";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['1'] = "Kies deze optie om de veiligheidsvraag uit te zetten (niet aanbevolen).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['0'] = "Archief beschermen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['1'] = "Laat galerij items alleen aan bepaalde ledengroepen zien.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['0'] = "Ledengroepen welke zijn toegestaan";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['1'] = "Hier kunt u kiezen welke groepen toegang hebben tot de galerij items van deze collectie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['0'] = "Genereer feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['1'] = "Genereer een RSS/Atom feed van deze galerij collectie.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['0'] = "Feed formaat";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['1'] = "Kies een feed formaat.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['0'] = "Taal";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['1'] = "Geef de taal op volgens het RCF1766 format (bv. en, en-us of en-cockney).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['0'] = "Export instellingen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['1'] = "Hier kunt u kiezen wat geexporteerd wordt.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['0'] = "Maximum aantal items";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['1'] = "Beperk het aantal geëxporteerde items. Blanco of 0 om alles te exporteren.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['0'] = "Basis URL";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['1'] = "Geef de basis URL inclusief het protocol op (b.v. http://).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['0'] = "Feed alias";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['1'] = "Hier kunt u een unieke feed naam opgeven. Een XML bestand zal automatisch in de root directory van uw Contao installatie worden aangemaakt (naam.xml).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['1'] = "Geef een korte omschrijving voor deze galerij feed.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['0'] = "Datum van aanpassing";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['1'] = "Datum en tijd van de laatste aanpassing";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_asc'] = "Bestandsnaam (oplopend)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_desc'] = "Bestandsnaam (aflopend)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_asc'] = "Datum (oplopend)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_desc'] = "Datum (aflopend)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['meta'] = "Meta bestand (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['random'] = "Willekeurige volgorde";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_admin'] = "Systeem administrateur";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_author'] = "Auteur van het galerij item";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_both'] = "Auteur en systeem administrateur";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sorting'] = "Handmatig sorteren";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_asc'] = "Titel (alfabetisch)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Titel, omschrijving en doorverwijzing naar een andere pagina";
$GLOBALS['TL_LANG']['tl_gallery_archive']['filter_legend'] = "Filter instellingen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups_legend'] = "Kunstenaars groepen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['image_legend'] = "Afbeeldingsinstellingen";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Reacties";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected_legend'] = "Toegangsrechten";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feed_legend'] = "RSS/Atom feed";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Nieuwe galerij collectie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Maak een nieuwe galerij collectie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Bewerk galerij collectie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Bewerk galerij collectie ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Dupliceer galerij collectie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Dupliceer galerij collectie ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Verwijder galerij collectie";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Verwijder galerij collectie ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Galerij collectie details";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Laat details zien van galerij collectie ID %s";
 
?>
