<?php
/**
 * TL_ROOT/system/modules/gallery/languages/nl/tl_module.php 
 * 
 * Contao extension: gallery 0.8.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Bart van Asperen (Vascom), www.vascom.nl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Galerij";
$GLOBALS['TL_LANG']['tl_module']['gallery']['1'] = "Selecteer een galerij om weer te geven.";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Galerij archieven";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['1'] = "Selecteer één of meer galerij archieven.";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "Meta-data velden";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['1'] = "Kies welke galerij meta-data velden weergegeven worden.";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Datum formaat";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['1'] = "Vul een datum formaat in zoals gebruikt door de PHP <em>datum()</em> functie.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "Sorteer volgorde";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['1'] = "Kies welk veld gebruikt wordt voor sortering van de galerij lijst.";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['0'] = "Filter instellen";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['1'] = "Laat de galerij lijst reageren op filter parameters.";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['0'] = "Filter velden toevoegen";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['1'] = "Voeg de volgende filter velden toe aan deze galerij lijst.";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['0'] = "Filter voorwaarden";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['1'] = "Selecteer op welke voorwaarden gefilterd kan worden.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "Totaal aantal galerij items";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['1'] = "Hier kan je het totaal aantal galerij items limiteren (0=alles weergeven).";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['0'] = "Items met bepaalde eigenschappen";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['1'] = "Laat alleen galerij items met een bepaalde eigenschap in de lijst zien";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['0'] = "Poster afbeelding breedte en hoogte";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['1'] = "Hier kan je het formaat van de Poster afbeelding instellen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['0'] = "Poster ware grootte";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['1'] = "Open de afbeelding op ware grootte in een lightbox of in een nieuw browser venster.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "Galerij afbeeldingen weergeven";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['1'] = "Voeg galerij afbeeldingen toe. Ook kunt u de standaard afbeeldingsinstellingen aanpassen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "Galerij afbeelding breedte en hoogtet";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['1'] = "Hier kan je het formaat van de afbeelding instellen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "Afbeeldingsmarge";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['1'] = "Geef een marge op voor boven, rechts, onder, en links van de afbeelding.";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['0'] = "Thumbnails per rij";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['1'] = "Geef het aantal thumbnails per rij op.";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['0'] = "Items per pagina";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['1'] = "Geef het aantal items per pagina op (0=uitzetten).";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['0'] = "Sorteer op";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['1'] = "Selecteer de sorteervolgorde.";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['0'] = "Ware grootte /nieuw venster";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['1'] = "Open de afbeelding op ware grootte in een lightbox of in een nieuw browser venster.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['0'] = "Totaal aantal afbeeldingen";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['1'] = "Hier kan je het totaal aantal galerij items limiteren (0=alles weergeven).";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "Galerij template";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['1'] = "Selecteer de galerij template.";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Galerij titel";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['1'] = "Geef een titel voor deze galerij.";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Breedte en hoogte";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['1'] = "Geef de breedte en hoogte op voor de Flash film.";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['0'] = "Slide interval";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['1'] = "Geef de slide interval in seconden op.";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "XML template";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['1'] = "Kies een XML template om de galerij te initialiseren.";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Pause en start";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['1'] = "Standaard de slideshow niet automatisch laten beginnen.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['default'] = "Standaard (galerij collectie instellingen)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_desc'] = "Datum (laatste eerst)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date_asc'] = "Datum (oudste eerst)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Titel (alfabetisch)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['sorting'] = "Handmatig sorteren";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Willekeurige volgorde";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_asc'] = "Bestandsnaam (oplopend)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_desc'] = "Bestandsnaam (aflopend)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['meta'] = "Meta bestand (meta.txt)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['author'] = "Auteur";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Locatie";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Datum";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artist'] = "Kunstenaar of fotograaf";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artsize'] = "Afmeting werk";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['medium'] = "Medium";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['substrate'] = "Ondergrond";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['comments'] = "Reacties";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['qty'] = "Afbeelding formaat";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "dfGallery instellingen";
$GLOBALS['TL_LANG']['tl_module']['filter_legend'] = "Filter instellingen";
 
?>
