<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fr/modules.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Galeries";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Galeries";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Liste de galeries";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Visionneur de galerie";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Galerie simple";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "Galerie dfGallery";
 
?>
