<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fr/tl_gallery.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Date";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Localisation";
$GLOBALS['TL_LANG']['tl_gallery']['photographer']['0'] = "Photographe";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Fichiers sources";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Vignettes par ligne";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Tri";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Eléments par page";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Marge de l'image";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Largeur et hauteur de l'image";
$GLOBALS['TL_LANG']['tl_gallery']['autorotate']['0'] = "Rotation automatique des vignettes";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Vue en taille réelle";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Publiée";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Désactiver les commentaires";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Nom de fichier (ascendant)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Nom de fichier (descendant)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Date (ascendant)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Date (descendant)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Fichier méta (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Titre, photographe, date, localisation et description";
$GLOBALS['TL_LANG']['tl_gallery']['source_legend'] = "Fichers et répertoires";
$GLOBALS['TL_LANG']['tl_gallery']['image_legend'] = "Paramètres de l'image";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Paramètres de publication";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Nouvelle galerie";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Créer une nouvelle galerie";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Editer la galerie";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Editer la galerieID %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Copier la galerie";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Copier la galerieID %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Supprimer la galerie";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Supprimer la galerieID %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Détails de la galerie";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Afficher les détails de la ID %s";
 
?>
