<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fr/tl_gallery_archive.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Aller à la page";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Autoriser les commentaires";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Présentation des commentaire";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Ordre de tri";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Eléments par page";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Modérer";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "Autoriser le BBCode";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Connexion requise";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Désactiver la question de sécurité";
$GLOBALS['TL_LANG']['tl_gallery_archive']['ascending'] = "acendant";
$GLOBALS['TL_LANG']['tl_gallery_archive']['descending'] = "descendant";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Titre, description et page de redirection";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Commentaires";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Nouvel album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Créer un nouvel album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Editer l'album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Editer l'album ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Copier l'album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Copier l'album ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Supprimer l'album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Supprimer l'album ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Détails de l'album";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Afficher les détails de l'album ID %s";
 
?>
