<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fr/tl_module.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Galerie";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Albums de galeries";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Format de la date";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Largeur et hauteur";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "Modèle XML";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Pause au démarrage";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date'] = "Date (plus récent en premier)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Titre (alphabétique)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Aléatoire (non ordonné)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Date";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Localisation";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['photographer'] = "Photographe";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['description'] = "Description";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "Paramètres de dfGallery";
 
?>
