<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fr/tl_user_group.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_group']['gallery_legend'] = "Permissions";
 
?>
