<?php
/**
 * TL_ROOT/system/modules/gallery/languages/ru/modules.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Pavel Prokopenko (mauldork) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "Галереи";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "Этот модуль управляет изображениями в галереях.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "Галереи";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "Список галерей";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "Этот модуль формирует список галерей согласно их архивам.";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "Просмотрщик галереи";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['1'] = "Этот модуль показывает изображения в галереи при переходе по ссылке в списке галерей.";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "Одиночная галерея";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['1'] = "Этот модуль позволяет создать модуль заданной галереи, который может быть включен в новости, события или статьи путем добавления тэга <em>{‎{insert_module::ID}}</em>.";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "Галерея dfGallery";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['1'] = "Этот модуль показывает все изображения галереи (используя flash-галерею dfGallery) при переходе по ссылке в списке галерей.";
 
?>
