<?php
/**
 * TL_ROOT/system/modules/gallery/languages/ru/tl_gallery.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Pavel Prokopenko (mauldork) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "Заголовок";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "Пожалуйста введите заголовок галереи.";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "Постоянная ссылка галереи";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['1'] = "Постоянная ссылка галереи является уникальной ссылкой, по которой страница с галерей может быть вызвана вместо ID галереи.";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "Дата";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "Пожалуйста, введите дату галереи.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "Место";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "Пожалуйста укажите название места.";
$GLOBALS['TL_LANG']['tl_gallery']['photographer']['0'] = "Фотограф";
$GLOBALS['TL_LANG']['tl_gallery']['photographer']['1'] = "Пожалуйста укажите имя фотографа.";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "Описание";
$GLOBALS['TL_LANG']['tl_gallery']['description']['1'] = "Пожалуйста укажите краткое описание галереи.";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "Исходные файлы";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['1'] = "Пожалуйста выберите один или несколько файлов или папкок (файлы в папке будут включены автоматически).";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "Миниатюр в ряду";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['1'] = "Пожалуйста укажите число миниатюр, выводимых в одном ряду.";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "Порядок сортировки";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "Пожалуйста, выберите порядок сортировки.";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "Записей на странице";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['1'] = "Пожалуйста, задайте число записей на странице (0 = запрет нумерации страниц).";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "Отступ изображения";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['1'] = "Укажите значение отступов сверху, справа, снизу и слева и единицу измерения. Отступ изображения - это расстояние между изображением и соседними элементами.";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "Ширина и высота изображения";
$GLOBALS['TL_LANG']['tl_gallery']['size']['1'] = "Введите ширину или высоту изображения для изменения размера, или оба значения сразу, чтобы обрезать изображение. Если оставить поля пустыми, изображение будет показано в оригинальном размере.";
$GLOBALS['TL_LANG']['tl_gallery']['autorotate']['0'] = "Австоматически переворачивать миниатюры'";
$GLOBALS['TL_LANG']['tl_gallery']['autorotate']['1'] = "Выберите эту опцию чтобы гарантировать, что повернутые фотографии будут показаны используя повернутые изменения размера.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "Просмотр в полный размер";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['1'] = "Позволяет показать изображение в полный размер при нажатии на него.";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "Опубликовать";
$GLOBALS['TL_LANG']['tl_gallery']['published']['1'] = "До тех пор, пока вы не выберете эту опцию, галерея не будет отображаться на сайте.";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "Отключить комментарии";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['1'] = "Отключить комментарии для этой галереи.";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "Имя файла (по возрастанию)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "Имя файла (по убыванию)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "Дата (по возрастанию)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "Дата (по убыванию)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "Мета файл (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "Заголовок, фотограф, дата, место и описание";
$GLOBALS['TL_LANG']['tl_gallery']['source_legend'] = "Файлы и папки";
$GLOBALS['TL_LANG']['tl_gallery']['image_legend'] = "Настройки изображения";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "Настройки публикации";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "Новая галерея";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "Создать новую галерею";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "Редактировать галерею";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "Редактировать галерею с ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "Копировать галерею";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "Копировать галерею с ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "Удалить галерею";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "Удалить галерею с ID %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "Детали галереи";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "Показать детали галереи с ID %s";
 
?>
