<?php
/**
 * TL_ROOT/system/modules/gallery/languages/ru/tl_gallery_archive.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Pavel Prokopenko (mauldork) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "Заголовок";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "Пожалуйста введите заголовок архива галерей.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "Описание";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "Пожалуйста введите описание архива галерей.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "Перейти на страницу";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['1'] = "Пожалуйста, выберите страницу, к которой посетители будут отправлены, при нажатии на галерею.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "Разрешить комментарии";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['1'] = "Разрешить вашим посетителям комментировать галереи.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "Макет комментария";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['1'] = "Пожалуйста, выберите макет для комментария. Файлы макетов комментария начинаются с <em>com_</em>.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "Порядок сортировки";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['1'] = "Пожалуйста, выберите порядок сортировки.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "Записей на странице";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['1'] = "Пожалуйста, задайте число комментариев на странице (0 = запрет нумерации страниц).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "Модерирование";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['1'] = "Одобрение комментариев перед тем, как они будут показаны на сайте.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "Разрешить BBCode";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['1'] = "Разрешить посетителям использовать BBCode, для форматирования своих комментариев.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "Требовать вход";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['1'] = "Не разрешать гостям создавать комментарии.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "Запретить контрольный вопрос";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['1'] = "Выберите данную опцию, чтобы отменить контрольный вопрос (не рекомендуется).";
$GLOBALS['TL_LANG']['tl_gallery_archive']['ascending'] = "по возрастанию";
$GLOBALS['TL_LANG']['tl_gallery_archive']['descending'] = "по убыванию";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "Заголовок, описание и переадресация";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "Комментарии";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "Новый архив галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "Создать новый архив галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "Редактировать архив галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "Редактировать архив галерей ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "Копировать архив галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "Копировать архив галерей ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "Удалить архив галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "Удалить архив галерей ID %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "Детали архива галерей";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "Показать детали архива ID %s";
 
?>
