<?php
/**
 * TL_ROOT/system/modules/gallery/languages/ru/tl_module.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Pavel Prokopenko (mauldork) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "Галерея";
$GLOBALS['TL_LANG']['tl_module']['gallery']['1'] = "Пожалуйста выберите галерею, которую нужно показать.";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "Архивы галерей";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['1'] = "Пожалуйста, выберите один или несколько архивов галерей.";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "Шаблон галереи";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['1'] = "Пожалуйста выберите макет галереи. Вы можете добавить свой макет в папку <em>templates</em>. Файлы шаблонов галереии начинаются с <em>gallery_</em> и требуют расширения <em>.tpl</em>.";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "Meta-данные";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['1'] = "Пожалуйста укажите какие поля meta-данных необходимо отобразить.";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "Формат даты";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['1'] = "Пожалуйста, введите формат даты, используемый PHP функцией <em>date()</em>.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "Поле сортировки";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['1'] = "Выберите поле для сортировки списка галерей.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showQuantity']['0'] = "Показывать количество изображений";
$GLOBALS['TL_LANG']['tl_module']['gallery_showQuantity']['1'] = "Если вы выберите эту опцию, то количество изображений в галереи будет показано сразу после ее заголовка.";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "Число галерей";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['1'] = "Пожалуйста, выберите количество галерей, которое нужно отображать. Введите 0, чтобы отображать все галереи.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "Показывать миниатюры";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['1'] = "Выберите эту опцию, чтобы добавить предпросмотр миниатюр (по умолчанию первый ряд) к каждой галереи. Вы можете задать размер мениатюр ниже.";
$GLOBALS['TL_LANG']['tl_module']['gallery_showRandom']['0'] = "Показывать только одно случайное изображение";
$GLOBALS['TL_LANG']['tl_module']['gallery_showRandom']['1'] = "Если вы выберите эту опцию, то одно случайное изображение будет использовано как миниатюра для галереи.";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "Отступ изображения";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['1'] = "Укажите значение отступов сверху, справа, снизу и слева и единицу измерения. Отступ изображения - это расстояние между изображением и соседними элементами.";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "Ширина и высота изображения";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['1'] = "Введите ширину или высоту изображения для изменения размера, или оба значения сразу, чтобы обрезать изображение. Если оставить поля пустыми, изображение будет показано в оригинальном размере.";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "Заголовок галереи";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['1'] = "Пожалуйста укажите заголовок галереи.";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "Ширина и высота";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['1'] = "Пожалуйста укажите ширину и высоту flash-ролика.";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['0'] = "Интервал между слайдами";
$GLOBALS['TL_LANG']['tl_module']['dfInterval']['1'] = "Пожалуйста укажите интервал между слайдами в секундах.";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "Шаблон XML";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['1'] = "ожалуйста выберите шаблон XML, чтобы инициализировать галерею.";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "Пауза при старте";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['1'] = "Не запускать слайд-шоу по умолчанию.";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['date'] = "Дата (последние первые)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "Заголовок (по алфавиту)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "Случайный (несортированно)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "Дата";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "Место";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['photographer'] = "Фотограф";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['description'] = "Описание";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "Настройки dfGallery";
 
?>
