<?php
/**
 * TL_ROOT/system/modules/gallery/languages/ru/tl_user.php 
 * 
 * TYPOlight extension: gallery 0.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Pavel Prokopenko (mauldork) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['galleries']['0'] = "Разрешенные архивы галерей";
$GLOBALS['TL_LANG']['tl_user']['galleries']['1'] = "Пожалуйста, выберите архивы галерей, которые вы хотите разрешить для посетителей.";
$GLOBALS['TL_LANG']['tl_user']['gallery_legend'] = "Разрешения галереи";
 
?>
