<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fa/modules.php 
 * 
 * Contao extension: gallery 0.8.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008-2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery']['0'] = "آلبوم‌ها";
$GLOBALS['TL_LANG']['MOD']['gallery']['1'] = "این ماژول تصاویر را در آلبوم‌ها مدیریت می‌کند.";
$GLOBALS['TL_LANG']['FMD']['gallery'] = "آلبوم‌ها";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['0'] = "لیست آلبوم";
$GLOBALS['TL_LANG']['FMD']['gallerylist']['1'] = "یک لیست از آیتم‌ها آلبوم را از یک مجموعه اضافه می‌کند.";
$GLOBALS['TL_LANG']['FMD']['gallerylistpage']['0'] = "لیست آلبوم توسط صفحه";
$GLOBALS['TL_LANG']['FMD']['galleryviewer']['0'] = "نمایش دهنده آلبوم";
$GLOBALS['TL_LANG']['FMD']['gallerysingle']['0'] = "آلبوم تکی";
$GLOBALS['TL_LANG']['FMD']['gallerydfgallery']['0'] = "آلبوم dfGallery";
 
?>
