<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fa/tl_gallery_archive.php 
 * 
 * Contao extension: gallery 0.8.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008-2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['0'] = "عنوان";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title']['1'] = "عنوان مجموعه آلبوم را وارد نمایید.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['0'] = "توصیف";
$GLOBALS['TL_LANG']['tl_gallery_archive']['description']['1'] = "توصیفی مختصر درباره مجموعه آلبوم وارد کنید.";
$GLOBALS['TL_LANG']['tl_gallery_archive']['jumpTo']['0'] = "پرش به صفحه";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortmode']['0'] = "حالت مرتب‌سازی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['pgFilter']['0'] = "فیلتر صفحه";
$GLOBALS['TL_LANG']['tl_gallery_archive']['artgroups']['0'] = "گروه‌های هنرمند";
$GLOBALS['TL_LANG']['tl_gallery_archive']['allowComments']['0'] = "فعال کردن نظرات";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify']['0'] = "اعلام کردن";
$GLOBALS['TL_LANG']['tl_gallery_archive']['template']['0'] = "صفحه بندی نظرات";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sortOrder']['0'] = "ترتیب مرتب‌سازی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['perPage']['0'] = "نظرات در هر صفحه";
$GLOBALS['TL_LANG']['tl_gallery_archive']['moderate']['0'] = "مناسب کردن نظرات";
$GLOBALS['TL_LANG']['tl_gallery_archive']['bbcode']['0'] = "اجازه دادن به BBCode";
$GLOBALS['TL_LANG']['tl_gallery_archive']['requireLogin']['0'] = "لزوم وارد شدن برا نظر دادن";
$GLOBALS['TL_LANG']['tl_gallery_archive']['disableCaptcha']['0'] = "غیرفعال کردن سوال امنیتی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected']['0'] = "حفاظت آرشیو";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups']['0'] = "گروه‌های اعضاء مجاز";
$GLOBALS['TL_LANG']['tl_gallery_archive']['makeFeed']['0'] = "ایجاد خوراک";
$GLOBALS['TL_LANG']['tl_gallery_archive']['format']['0'] = "قالب خوراک";
$GLOBALS['TL_LANG']['tl_gallery_archive']['language']['0'] = "زبان خوراک";
$GLOBALS['TL_LANG']['tl_gallery_archive']['source']['0'] = "تنظیمات پیشرفته";
$GLOBALS['TL_LANG']['tl_gallery_archive']['maxItems']['0'] = "تعداد بیشینه آیتم‌ها";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feedBase']['0'] = "ادرس مبداء";
$GLOBALS['TL_LANG']['tl_gallery_archive']['alias']['0'] = "اسم مستعار خوراک";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feeddescription']['0'] = "توضیحات خوراک";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['0'] = "تاریخ بازنگری";
$GLOBALS['TL_LANG']['tl_gallery_archive']['tstamp']['1'] = "تاریخ و ساعت آخرین بازنگری";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_asc'] = "نام فایل (صعودی)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['name_desc'] = "نام فایل (نزولی)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_asc'] = "تایخ (صعودی)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['date_desc'] = "تاریخ (نزولی)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['meta'] = "فایل متا (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['random'] = "ترتیب تصادفی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_admin'] = "مدیر سیستم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_author'] = "نویسنده آیتم آلبوم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['notify_both'] = "نویسنده و مدیر سیستم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['sorting'] = "مرتیب‌سازی دستی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_asc'] = "عنوان (الفبا)";
$GLOBALS['TL_LANG']['tl_gallery_archive']['title_legend'] = "عنوان، توضیح و صفحه هدایت";
$GLOBALS['TL_LANG']['tl_gallery_archive']['filter_legend'] = "تنظیمات فیلتر";
$GLOBALS['TL_LANG']['tl_gallery_archive']['groups_legend'] = "گروه‌های هنری";
$GLOBALS['TL_LANG']['tl_gallery_archive']['image_legend'] = "تنظیمات پیش‌فرض تصویر";
$GLOBALS['TL_LANG']['tl_gallery_archive']['comments_legend'] = "نظرات";
$GLOBALS['TL_LANG']['tl_gallery_archive']['protected_legend'] = "حفاظت دسترسی";
$GLOBALS['TL_LANG']['tl_gallery_archive']['feed_legend'] = "خوراک RSS/Atom";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['0'] = "مجموعه آلبوم جدید";
$GLOBALS['TL_LANG']['tl_gallery_archive']['new']['1'] = "ایجاد مجموعه آلبوم جدید";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['0'] = "ویرایش مجموعه آلبوم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['edit']['1'] = "ویرایش مجموعه آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['0'] = "کپی مجموعه آلبوم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['copy']['1'] = "کپی مجموعه آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['0'] = "حذف مجموعه آلبوم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['delete']['1'] = "حذف مجموعه آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['0'] = "جزئیات مجموعه آلبوم";
$GLOBALS['TL_LANG']['tl_gallery_archive']['show']['1'] = "نمایش جزئیات مجموعه آلبوم شناسه %s";
 
?>
