<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fa/tl_gallery.php 
 * 
 * Contao extension: gallery 0.8.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008-2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery']['title']['0'] = "عنوان";
$GLOBALS['TL_LANG']['tl_gallery']['title']['1'] = "عنوان آلبوم را وارد کنید";
$GLOBALS['TL_LANG']['tl_gallery']['alias']['0'] = "اسم مستعار آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['date']['0'] = "تاریخ";
$GLOBALS['TL_LANG']['tl_gallery']['date']['1'] = "تاریخ آلبوم را وارد نمایید.";
$GLOBALS['TL_LANG']['tl_gallery']['author']['0'] = "نویسنده";
$GLOBALS['TL_LANG']['tl_gallery']['author']['1'] = "می‌توانید نویسنده آیتم‌های آلبوم را تغییر دهید.";
$GLOBALS['TL_LANG']['tl_gallery']['location']['0'] = "موقعیت";
$GLOBALS['TL_LANG']['tl_gallery']['location']['1'] = "نام موقعیت را وارد کنید";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['0'] = "عضو هنرمند یا عکاس";
$GLOBALS['TL_LANG']['tl_gallery']['artist']['1'] = "هنرمند یا عکاس را انتخاب کنید. (از اعضاء)";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['0'] = "اندازه اثر هنری";
$GLOBALS['TL_LANG']['tl_gallery']['artsize']['1'] = "اندازه مانند عرض، ارتفاع و واحد را وارد نمایید.";
$GLOBALS['TL_LANG']['tl_gallery']['medium']['0'] = "رسانه";
$GLOBALS['TL_LANG']['tl_gallery']['substrate']['0'] = "زیرلایه";
$GLOBALS['TL_LANG']['tl_gallery']['description']['0'] = "توضیحات";
$GLOBALS['TL_LANG']['tl_gallery']['singleSRC']['0'] = "تصویر پوستر";
$GLOBALS['TL_LANG']['tl_gallery']['multiSRC']['0'] = "فایل‌های تصویر آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['setImages']['0'] = "لغو کردن تنظیمات تصویر پیش‌فرض";
$GLOBALS['TL_LANG']['tl_gallery']['posterSize']['0'] = "عرض و ارتفاع تصویر پوستر";
$GLOBALS['TL_LANG']['tl_gallery']['posterFullsize']['0'] = "نمایش تمام صفحه پوستر";
$GLOBALS['TL_LANG']['tl_gallery']['size']['0'] = "عرض و ارتفاع تصاویر آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['imagemargin']['0'] = "حاشیه تصاویر آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['perRow']['0'] = "تصویر بندانگشتی در هر ردیف";
$GLOBALS['TL_LANG']['tl_gallery']['perPage']['0'] = "آیتم در هر صفحه";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['0'] = "مرتب‌سازی براساس";
$GLOBALS['TL_LANG']['tl_gallery']['sortBy']['1'] = "نوع مرتب‌سازی را انتخاب کنید.";
$GLOBALS['TL_LANG']['tl_gallery']['fullsize']['0'] = "نمایش تمام صفحه";
$GLOBALS['TL_LANG']['tl_gallery']['cssClass']['0'] = "کلاس CSS";
$GLOBALS['TL_LANG']['tl_gallery']['status']['0'] = "وضعیت";
$GLOBALS['TL_LANG']['tl_gallery']['noComments']['0'] = "غیرفعال کردن نظرات";
$GLOBALS['TL_LANG']['tl_gallery']['featured']['0'] = "آیتم ویژه";
$GLOBALS['TL_LANG']['tl_gallery']['published']['0'] = "انتشار آیتم";
$GLOBALS['TL_LANG']['tl_gallery']['start']['0'] = "نمایش از";
$GLOBALS['TL_LANG']['tl_gallery']['stop']['0'] = "نمایش تا";
$GLOBALS['TL_LANG']['tl_gallery']['name_asc'] = "نام فایل (صعودی)";
$GLOBALS['TL_LANG']['tl_gallery']['name_desc'] = "نام فایل (نزولی)";
$GLOBALS['TL_LANG']['tl_gallery']['date_asc'] = "تاریخ (قدیم به جدید)";
$GLOBALS['TL_LANG']['tl_gallery']['date_desc'] = "تاریخ (جدید به قدیم)";
$GLOBALS['TL_LANG']['tl_gallery']['meta'] = "فایل متا (meta.txt)";
$GLOBALS['TL_LANG']['tl_gallery']['random'] = "تصادفی";
$GLOBALS['TL_LANG']['tl_gallery']['oil'] = "رنگ روغن";
$GLOBALS['TL_LANG']['tl_gallery']['acr'] = "آکرلیک";
$GLOBALS['TL_LANG']['tl_gallery']['ola'] = "رنگ روغن و آکرلیک";
$GLOBALS['TL_LANG']['tl_gallery']['mpt'] = "چاپ تک‌رنگ";
$GLOBALS['TL_LANG']['tl_gallery']['cpt'] = "چاپ رنگی";
$GLOBALS['TL_LANG']['tl_gallery']['cvs'] = "بوم نقاشی";
$GLOBALS['TL_LANG']['tl_gallery']['ppr'] = "کاغذ";
$GLOBALS['TL_LANG']['tl_gallery']['pho'] = "عکس";
$GLOBALS['TL_LANG']['tl_gallery']['vnl'] = "وینیل";
$GLOBALS['TL_LANG']['tl_gallery']['brd'] = "تابلو";
$GLOBALS['TL_LANG']['tl_gallery']['fab'] = "فابرینو";
$GLOBALS['TL_LANG']['tl_gallery']['avail'] = "موجود";
$GLOBALS['TL_LANG']['tl_gallery']['sold'] = "فروخته شد";
$GLOBALS['TL_LANG']['tl_gallery']['resv'] = "محفوظ";
$GLOBALS['TL_LANG']['tl_gallery']['title_legend'] = "اطلاعات عنوان و دیگر توضیحات";
$GLOBALS['TL_LANG']['tl_gallery']['poster_legend'] = "تصویر پوستر";
$GLOBALS['TL_LANG']['tl_gallery']['gallery_legend'] = "تصاویر آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['groups_legend'] = "گروه‌های هنرمند";
$GLOBALS['TL_LANG']['tl_gallery']['expert_legend'] = "تنظیمات پیشرفته";
$GLOBALS['TL_LANG']['tl_gallery']['publish_legend'] = "تنظیمات انتشار";
$GLOBALS['TL_LANG']['tl_gallery']['new']['0'] = "آلبوم جدید";
$GLOBALS['TL_LANG']['tl_gallery']['new']['1'] = "ایجاد آلبوم جدید";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['0'] = "ویرایش آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['edit']['1'] = "ویرایش آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['0'] = "کپی آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['copy']['1'] = "کپی آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['0'] = "حذف آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['delete']['1'] = "حذف آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery']['show']['0'] = "جزئیات آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['show']['1'] = "جزئیات آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['0'] = "انتشار/عدم انتشار آلبوم";
$GLOBALS['TL_LANG']['tl_gallery']['toggle']['1'] = "انتشار/عدم انتشار آلبوم شناسه %s";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['0'] = "ویرایش تنظیمات مجموعه";
$GLOBALS['TL_LANG']['tl_gallery']['editheader']['1'] = "ویرایش تنظیمات مجموعه آلبوم";
 
?>
