<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fa/tl_layout.php 
 * 
 * Contao extension: gallery 0.8.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008-2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['galleryfeeds']['0'] = "خوراک آلبوم";
 
?>
