<?php
/**
 * TL_ROOT/system/modules/gallery/languages/fa/tl_module.php 
 * 
 * Contao extension: gallery 0.8.2 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008-2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['gallery']['0'] = "آلبوم";
$GLOBALS['TL_LANG']['tl_module']['gallery_archives']['0'] = "آرشیو آلبوم";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaFields']['0'] = "فیلدهای داده‌های متا";
$GLOBALS['TL_LANG']['tl_module']['gallery_dateFormat']['0'] = "قالب تاریخ";
$GLOBALS['TL_LANG']['tl_module']['gallery_sort']['0'] = "ترتیب مرتب‌سازی";
$GLOBALS['TL_LANG']['tl_module']['gallery_enableFilter']['0'] = "فعال کردن پشتیبانی فیلتر";
$GLOBALS['TL_LANG']['tl_module']['gallery_filters']['0'] = "اضافه کردن فیلترهای فیلدی";
$GLOBALS['TL_LANG']['tl_module']['gallery_conditions']['0'] = "فیلتر کردن با شرایط";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfItems']['0'] = "تعداد کل آیتم‌های آلبوم";
$GLOBALS['TL_LANG']['tl_module']['gallery_featured']['0'] = "فقط آیتم‌های ویژه";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterSize']['0'] = "عرض و ارتفاع تصویر پوستر";
$GLOBALS['TL_LANG']['tl_module']['gallery_posterFullsize']['0'] = "نمایش کامل پوستر";
$GLOBALS['TL_LANG']['tl_module']['gallery_showPreview']['0'] = "نمایش تصاویر آلبوم";
$GLOBALS['TL_LANG']['tl_module']['gallery_size']['0'] = "عرض و ارتفاع تصاویر آلبوم";
$GLOBALS['TL_LANG']['tl_module']['gallery_imagemargin']['0'] = "حاشیه تصویر";
$GLOBALS['TL_LANG']['tl_module']['gallery_perRow']['0'] = "بندانگشتی در هر ردیف";
$GLOBALS['TL_LANG']['tl_module']['gallery_perPage']['0'] = "آیتم‌ها در هر صفحه";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortBy']['0'] = "مرتب کردن با";
$GLOBALS['TL_LANG']['tl_module']['gallery_fullsize']['0'] = "نمایش کامل";
$GLOBALS['TL_LANG']['tl_module']['gallery_numberOfImages']['0'] = "تعداد کل تصاویر";
$GLOBALS['TL_LANG']['tl_module']['gallery_template']['0'] = "الگوی آلبوم";
$GLOBALS['TL_LANG']['tl_module']['dfTitle']['0'] = "عنوان آلبوم";
$GLOBALS['TL_LANG']['tl_module']['dfSize']['0'] = "عرض و ارتفاع";
$GLOBALS['TL_LANG']['tl_module']['dfTemplate']['0'] = "قالب XML";
$GLOBALS['TL_LANG']['tl_module']['dfPause']['0'] = "توقف در شروع";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['title'] = "عنوان (البفایی)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['sorting'] = "مرتب‌سازی دستی";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['random'] = "ترتیب تصادفی";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_asc'] = "نام فایل (صعودی)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['name_desc'] = "نام فایل (نزولی)";
$GLOBALS['TL_LANG']['tl_module']['gallery_sortval']['meta'] = "فایل متا (meta.txt)";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['author'] = "نویسنده";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['location'] = "موقعیت";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['status'] = "وضعیت";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['date'] = "تاریخ";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artist'] = "هنرمند عکاس";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['artsize'] = "اندازه کار هنری";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['medium'] = "رسانه";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['substrate'] = "لایه";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['comments'] = "نظرها";
$GLOBALS['TL_LANG']['tl_module']['gallery_metaval']['qty'] = "کمیت تصویر";
$GLOBALS['TL_LANG']['tl_module']['dfconfig_legend'] = "تنظیمات dfGallery";
$GLOBALS['TL_LANG']['tl_module']['filter_legend'] = "تنظیمات فیلتر";
 
?>
